# Generated by Django 6.0.3 on 2026-03-10 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=500)),
                ('ticker', models.CharField(default='UNKNOWN', max_length=50)),
                ('total_rows', models.IntegerField(default=0)),
                ('date_column', models.CharField(default='Date', max_length=100)),
                ('target_column', models.CharField(default='Close', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('columns_json', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('lstm', 'LSTM Deep Learning'), ('gru', 'GRU Deep Learning'), ('transformer', 'Transformer Model'), ('rf', 'Random Forest'), ('xgboost', 'XGBoost'), ('ensemble', 'Ensemble (DL + ML)')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('model_path', models.CharField(blank=True, max_length=500)),
                ('scaler_path', models.CharField(blank=True, max_length=500)),
                ('lookback_window', models.IntegerField(default=60)),
                ('epochs', models.IntegerField(default=50)),
                ('batch_size', models.IntegerField(default=32)),
                ('forecast_days', models.IntegerField(default=30)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('training_log', models.TextField(default='')),
                ('error_message', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='market_app.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_days', models.IntegerField(default=30)),
                ('dates_json', models.TextField(default='[]')),
                ('predicted_values_json', models.TextField(default='[]')),
                ('actual_values_json', models.TextField(default='[]')),
                ('lower_bound_json', models.TextField(default='[]')),
                ('upper_bound_json', models.TextField(default='[]')),
                ('historical_dates_json', models.TextField(default='[]')),
                ('historical_values_json', models.TextField(default='[]')),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('trend', models.CharField(default='neutral', max_length=20)),
                ('signal', models.CharField(default='hold', max_length=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='market_app.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='market_app.predictionmodel')),
            ],
        ),
    ]
